doukutsu-rs/doukutsu-rs

- src/player.rs
First try at adding something to the repo!
I tried keeping true to the source code [here](https://github.com/Clownacy/CSE2/blob/ab217f7f6fb84b7fed76fad366c8838c5215a1ed/src/MyChar.cpp#L603-L637)
I'm unsure of what the gMC.flag & 8 was so its commented.
the variable declarations seem superfluous and are only there for visibility. I can remove them easily. 
I attempted to condense the code (not need to rewrite the loop multiple times)
Let me know how i went :) Any coding conventions that are wrong etc.
> feat: add splash

- Cargo.toml
- src/components/stage_select.rs
- src/input/dummy_player_controller.rs
- src/input/keyboard_player_controller.rs
- src/input/player_controller.rs
- src/input/touch_player_controller.rs
- src/settings.rs
- src/text_script.rs
these should probably be split into their own prs but they're so small they could probably just be reviewed in one go
i'm not entirely sure what the skip text button should be for p2 and the touchscreen option is completely unimplemented. also i didn't go through every single dialog in the game to test it, but it shouldn't actually break anything because it doesn't skip wait events
> collection of minor stuff

- src/lib.rs
should fix some panics that only happen on windows
> Mitigations for Windows quirks

- src/scene/game_scene.rs
Fixes the Yes/No dialog box flying from above and too fast.
> fix Yes/No animation

- src/components/background.rs
- src/components/nikumaru.rs
- src/npc/ai/mimiga_village.rs
- src/npc/ai/misc.rs
- src/npc/boss/ironhead.rs
- src/npc/mod.rs
- Added Ikachan NPCs
- Fixed Ironhead's movement 
- Fixed Ironhead's block projectiles
- Implemented scrolling background with interpolation
> Ironhead bugfixes + Ikachan NPC

- src/npc/ai/hell.rs
- src/npc/boss/ballos.rs
- src/npc/boss/heavy_press.rs
- src/scene/game_scene.rs
- Stop inventory from opening during scripts
- Moved heavy press on Switch maps
- Butes no longer get stuck in walls when spawning
- Fixed Ballos's leaving animation
> Minor fixes

- src/npc/boss/ironhead.rs
- src/scene/game_scene.rs
- Set clip for Ironhead control mode to center 320x240
> Ironhead letterbox

- src/components/nikumaru.rs
- src/menu/pause_menu.rs
- src/scene/title_scene.rs
- src/scripting/tsc/text_script.rs
> STC command Save/Load

- src/scripting/tsc/text_script.rs
- src/sound/mod.rs
- src/sound/pixtone.rs
- Implemented SSS command's operand to loop SFX at set frequency 
https://user-images.githubusercontent.com/96957561/150656682-080226c7-6ecf-438f-aaa3-a7fbbc27cbf4.mp4
> SSS operand implemented

- src/engine_constants/mod.rs
- src/menu/mod.rs
- src/menu/settings_menu.rs
- src/settings.rs
- src/shared_game_state.rs
- src/sound/mod.rs
https://user-images.githubusercontent.com/96957561/151668748-f055d804-b41d-469a-8bb2-8640b2fb16f8.mp4
> Added volume settings

- src/menu/mod.rs
- src/menu/save_select_menu.rs
- src/scene/title_scene.rs
- src/shared_game_state.rs
https://user-images.githubusercontent.com/96957561/152626259-e91b1ce2-94bb-4a56-a5d7-ec58e6863cf1.mp4
> Added save select menu

- src/scene/jukebox_scene.rs
Jukebox will now start with the selected soundtrack. Also required rewriting the wrap-around logic for soundtrack switching a bit.
Chevrons at the top will now indicate that you can switch between soundtracks.
> make jukebox start with selected soundtrack + chevrons

- src/engine_constants/mod.rs
- src/menu/settings_menu.rs
- src/scene/jukebox_scene.rs
- src/shared_game_state.rs
- src/sound/mod.rs
Extra (CS+) soundtracks are no longer bound to the kind of data files that you're using and will only load if they exist on the file system.
> refactor CS+ soundtrack loading

- src/shared_game_state.rs
additional detection for the other commercial ports of Cave Story, colored text and notes which may help anyone who'd want to support these
> Unique Data detection

- src/engine_constants/mod.rs
- src/scene/title_scene.rs
- src/shared_game_state.rs
fixes #85 
Changing soundtracks absolutely breaks it but whatever.
> add ikachan title theme

- src/scene/game_scene.rs
https://user-images.githubusercontent.com/53099651/160294199-f4250205-2a2b-4144-a5ac-fa20311d5db7.mp4
> SPD debug text + slight alignment

- src/builtin/locale/en.json
- src/builtin/locale/jp.json
- src/live_debugger.rs
- src/menu/coop_menu.rs
- src/menu/mod.rs
- src/menu/save_select_menu.rs
- src/player/skin/basic.rs
- src/player/skin/mod.rs
- src/scene/game_scene.rs
- src/scene/title_scene.rs
- src/shared_game_state.rs
adds an option to select the number of players in both the load confirm menu and after selecting the difficulty, in addition to costume selection.
> add coop menu

- README.md
using the more complete one from the CSMC
> re-add wiiware extraction guide

- src/builtin/builtin_data/locale/en.json
- src/builtin/builtin_data/locale/jp.json
- src/menu/settings_menu.rs
Adds a menu to Cave Story websites and resources
> Add Links Menu

- src/components/number_popup.rs
- src/game/npc/boss/mod.rs
- src/game/npc/mod.rs
- src/game/npc/utils.rs
- src/game/player/mod.rs
- src/game/player/player_hit.rs
- src/scene/game_scene.rs
Not perfect but I think this is about as close as it's going to get
> Fix number popup bugs from #163

- src/game/npc/ai/egg_corridor.rs
- src/game/npc/ai/first_cave.rs
- src/game/npc/ai/grasstown.rs
- src/game/npc/ai/mimiga_village.rs
- src/game/npc/boss/balfrog.rs
mfw the angle math is in degrees instead of radians
> Accuracy fixes for First Cave through Grasstown

- src/game/npc/ai/balcony.rs
- src/game/npc/ai/doctor.rs
- src/game/npc/ai/hell.rs
- src/game/npc/ai/igor.rs
- src/game/npc/ai/last_cave.rs
- src/game/npc/ai/misery.rs
- src/game/npc/ai/plantation.rs
- src/game/npc/boss/ballos.rs
- src/game/npc/boss/heavy_press.rs
- src/game/npc/boss/ironhead.rs
- src/game/npc/boss/undead_core.rs
- src/game/npc/mod.rs
Still have characters and miscellaneous entities remaining to be checked...
> Accuracy fixes for Waterway through Hell

- src/game/npc/ai/doctor.rs
- src/game/npc/ai/misc.rs
- src/game/npc/mod.rs
Wherein the hermit gunsmith finally learns how to blink.
Also fixes (I think) the "Red Crystal subtly flickers invisibly at random" issue from #114. Also from that issue, the downwards-facing fans being flipped seems to have already been fixed previously so that one can be marked off as well.
> Accuracy fixes for misc NPCs

- src/game/npc/ai/maze.rs
(Fixes #243)
Had this sitting on my computer for however long it's been now, finally decided that I may as well make a PR even though it's just a simple one-line change. There are probably more of these types of bugs lying around that have yet to be discovered.
> Fix Labyrinth M crash in debug builds

- src/components/credits.rs
- src/components/falling_island.rs
- src/engine_constants/mod.rs
- src/game/shared_game_state.rs
- src/game/stage.rs
- src/scene/game_scene.rs
The intro scene should have a black background, not dark blue.
(fixed image)
> Fix intro background color

- src/game/npc/ai/characters.rs
Mainly NPCs 326 (Itoh/Sue turning human) and 327 (sneeze speech bubble)
> Fix inaccuracies in characters.rs

- src/sound/mod.rs
- src/sound/org_playback.rs
- src/sound/wav.rs
- src/sound/wave_bank.rs
Reverts doukutsu-rs/doukutsu-rs#336
> Revert "sound: reuse buffers"
