- src/player/player_hit.rs
- src/scene/game_scene.rs
- src/text_script.rs
Fixed inaccuracies include:
1. Upon interacting with an NPC, the interaction flag is no longer immediately reset
2. Upon <TRA, the interaction flag is reset
3. Upon <MYB, the interaction flag is reset (Otherwise upon talking to toroko it would fling the player, but then they would stay in the interaction pose
4. Upon <MYD, interation flag is reset
5. Upon closing of the inventory, interaction flag is reset (Todo: Maybe in vanilla its upon opening? Didnt check)
> Fixed various inaccuracies regarding player interaction

- src/components/nikumaru.rs
- src/npc/ai/mimiga_village.rs
The nikumaru counter should be stopped any time the player does not have control (map changes, cutscenes, etc).
> Stop nikumaru counter while not in control

- src/menu/mod.rs
- src/menu/settings_menu.rs
- consistent 14/7 pixel spacing between option and selected value
- fixed small bug in audio menu where cursor would select the first entry, despite being un-selectable
- gave **`MenuEntry:Options`** an additional **`Vec<String>`** for hopefully better descriptions
- removed _"Player's"_ from _"Player's Weapon Light Cone"_ over redundancy and so it'd fit
> small start menu fixes

- src/menu/settings_menu.rs
The soundtrack menu will now save your selection and the cursor will default to the active soundtrack when you open the menu.
> Soundtrack menu improvements

- src/common.rs
- src/engine_constants/mod.rs
- src/menu/mod.rs
- src/menu/save_select_menu.rs
- src/npc/ai/misc.rs
- src/player/mod.rs
- src/player/skin/basic.rs
- src/player/skin/mod.rs
- src/profile.rs
- src/scene/title_scene.rs
- src/shared_game_state.rs
Difficulties work the same way as in CS+, meaning:
- easy difficulty will halve the damage you take
- hard difficulty will remove life capsules (except for the puppy capsule) and missile chests
The difficulties can be selected using any data files (including freeware), with the exception that difficulty-based skins will only be applied if you've loaded up CS+ data files and have original textures set to off.
Creating a new game now brings up a difficulty selection screen:
Skins will vary based on difficulty (however, original and seasonal textures will always take precedence). This modification is done to the basic player skin, so it doesn't lock the logic to the global skin structure.
Difficulties are also saved in the profile (in the same way and byte offset CS+ stores them).
In the …
> add CS+ game difficulties

- src/scripting/tsc/compiler.rs
Events that have stray bytes between an event and the start of another event did not get compiled. The change makes it so any byte apart from #, <, and newline chars will not disable the compilation of subsequent events. Instead, it will let whatever's before these bytes to say whether or not the next events should be parsed (tldr: it shouldn't break anything).
Example for an event that didn't get compiled because of this:
Fixes #73.
> prevent stray bytes from disallowing subsequent events

- src/menu/mod.rs
Moved the calculation of `entry_y` from the tick method to the draw method and made it a local variable instead of a struct property. This ensures the correct entry_y will be applied every time and the selected item cursor won't snap into place after the first frame (see #67).
Tbh not sure why `entry_y` was a struct property in the first place, since it's not really used anywhere else other than the drawing logic (which should be in the draw method anyway).
> fix menu selection snapping on first tick

- src/builtin/locale/en.json
- src/builtin/locale/jp.json
- src/builtin_fs.rs
- src/components/map_system.rs
- src/engine_constants/mod.rs
- src/i18n.rs
- src/lib.rs
- src/menu/mod.rs
- src/menu/pause_menu.rs
- src/menu/save_select_menu.rs
- src/menu/settings_menu.rs
- src/scene/game_scene.rs
- src/scene/jukebox_scene.rs
- src/scene/title_scene.rs
- src/settings.rs
- src/shared_game_state.rs
- src/stage.rs
This PR adds support for:
- JSON-based UI localization
- Japanese UI translation
- Loading the game in different languages
- Japanese stage names
- Dynamic menu widths to prevent text overflow
Notes: the CS+ Japanese font is messed up, until we figure out what's going on with it, the engine will fallback to the builtin font when the Japanese language is selected.
> Basic i18n support

- src/lib.rs
- src/mod_list.rs
- src/mod_requirements.rs
- src/profile.rs
- src/scene/title_scene.rs
- src/scripting/tsc/text_script.rs
- src/shared_game_state.rs
Challenges can be unlocked now based on their requirements.
- This data will persist in a ~~binary file called `mod.req`~~ JSON file called `mod_req.json`, so even if you delete your save files, the challenges will remain unlocked (like on CS+Switch)
- Fixed challenge data parser reading the wrong item/weapon ID requirement (it was offset by 1 char)
- Item and weapon requirements will be imported from save files but only if you load them up
- Item requirements will be added on each `<IT+` call\*
- Weapon requirements will be added on each `<AM+` call\*
- Hell requirement will be enabled once `<XX1` is called and while getting the best ending\*
- ~~`mod.req`~~ `mod_req.json` files are versioned in a way that's similar to the settings file
\*) Every time you get a new item/weapon or beat …
> add challenge unlocking

- .appveyor.yml
- README.md
- Fixed macOS quarantine problem by codesigning the doukutsu-rs binary (inside of doukutsu-rs.app)
- Updated the macOS note in the README accordingly to tell users how to run the unverified binary.
> codesign macOS builds

- src/scene/title_scene.rs
Replace the Cave Story logo beyond the Title Menu with window titles
> Menu titles

- src/engine_constants/mod.rs
- src/scene/title_scene.rs
- src/shared_game_state.rs
Makes DEMO data fully playable.
- Set the correct starting Event and Stage
- Add splash rect for the DEMO graphic
- Fix CS+ data from tiling ogph title
- Credit.tsc is now optional (thanks joe)
> Proper wiiware DEMO support

- src/menu/settings_menu.rs
Very small fix but it's been bugging me for a while. Allows the use of the left and right arrows to change the BGM Interpolation setting. On previous builds trying to change it would cause the *bwip!* sound to play but the actual setting would not change.
> Fix changing BGM Interpolation setting with left and right keys

- src/npc/ai/misc.rs
Looks like it was just using the n097_fan_up animation instead of n099_fan down.
> Fix downward facing fans pointing upwards

- src/scene/game_scene.rs
Changing map key enable from a hardcode to item 2 to the actual vanilla behavior of checking for equip flag. Tested in-game.
(Found because I have a mod that uses item 2 for something else).
> Map System Equip fix

- src/framework/backend_sdl2.rs
Import `crate::framework::render_opengl` causes crash when feature `render-opengl` is disabled
> Fix 'render_opengl' import when 'render-opengl' feature is disabled

- .appveyor.yml
Builds for Android and Horizon aren't currently configured, so starting the build after changing these files is useless(maybe someone will fix this later)
> Skip appveyor builds for android and horizon

- src/game/npc/ai/misery.rs
It was using the other `atan` function???
> Fix Misery bubble going the wrong way

- src/game/npc/ai/balrog.rs
- src/game/npc/ai/hell.rs
- src/game/npc/boss/heavy_press.rs
- src/game/npc/mod.rs
- src/game/scripting/tsc/text_script.rs
Is there some technical reason why the `change_tile` function doesn't just spawn the smoke itself? This seems a bit messy to do it this way...
> Make all CMPs generate the correct amount of smoke

- src/data/vanilla.rs
The only physicalFS loaded at this point uses `./data/` already as its root, so it checked for `./data/data/stage.sect`, which is wrong.
As a result, the game would re-extract the vanilla executable files every launch as long as the default exe was in the same directory.
> Fix vanilla executable extraction bug

- src/framework/render_opengl.rs
glFinish waits until rendering is complete.
This should only be required on single buffered output which I don't think we have.
Removing it improves performance on (very) low end hardware.
> Remove glFinish
